language: ruby
script: bundle exec rake
sudo: false
cache: bundler

rvm:
- 2.2.2
- 2.3.1
- 2.4.0

gemfile:
- Gemfile
- gemfiles/activesupport42.gemfile
- gemfiles/activesupport42_nokogiri_17.gemfile
- gemfiles/activesupport50.gemfile
- gemfiles/activesupport51.gemfile
- gemfiles/activesupport52.gemfile

matrix:
  exclude:
    - rvm: 2.4.0
      gemfile: gemfiles/activesupport42.gemfile
