language: ruby
script: bundle exec rake
sudo: false
cache: bundler

rvm:
- 2.0
- 2.1
- 2.2.2
- 2.3.1

gemfile:
- Gemfile
- gemfiles/activesupport32.gemfile
- gemfiles/activesupport40.gemfile
- gemfiles/activesupport41.gemfile
- gemfiles/activesupport42.gemfile
- gemfiles/activesupport50.gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.0
      gemfile: gemfiles/activesupport50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activesupport50.gemfile
